metadata:
  name: ${project.artifactId}-${app.bg.version}
  labels:
    app: ${project.artifactId}-${app.bg.version}
    group: ${project.groupId}
    project: ${project.artifactId}-${app.bg.version}
    provider: jkube
    expose: "true"
spec:
  type: ${jkube.enricher.jkube-service.type}
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    deploymentconfig: ${project.artifactId}-${app.bg.version}
